### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by onurcanyilmaz** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#11]
Hi again @wakuflair 

I downloaded a  new  abp project. In that:

![create_project](https://user-images.githubusercontent.com/33642676/82808461-b823f700-9e92-11ea-8598-6eb8fbafef92.PNG)

Well,  I installed your last nuget package 0.6.3 and i added dependsOn  and I run the application, 

![pls](https://user-images.githubusercontent.com/33642676/82808811-66c83780-9e93-11ea-865a-1f987e034b93.PNG)

 but I encountered an error that:

![ancm](https://user-images.githubusercontent.com/33642676/82808735-3b454d00-9e93-11ea-960f-396b786c7023.PNG)

 I think version problem. Your fix better than. Because didn't exist before

Can you help me?, I want use to the this template.
Thanks.

**Comment by wakuflair** [comment]
Did your project startup normally before using theme module？

**Comment by onurcanyilmaz** [comment]
Yes.  started normally before. 
Later, i m installed nuget package and added for dependson. 
Project give this error to screen

**Comment by wakuflair** [comment]
Please try the latest nuget pakcage(0.6.4).
