### ISSUE TITLE
fonts.cat waiting for a long time

### ISSUE THREAD

**Issue by onurcanyilmaz** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#12]
Hello @wakuflair 

Firstly, thank you .
I noticed this at first.

This url 

> https://fonts.cat.net/css?family=Source+Sans+Pro:300,400,400i,700 
giving to connection timeout error 522 

here:
![font_css](https://user-images.githubusercontent.com/33642676/82903567-d1e43d80-9f69-11ea-9ef5-71521ac84ba7.PNG)

Look at dev tools :
![font_css2](https://user-images.githubusercontent.com/33642676/82903712-06f09000-9f6a-11ea-99c0-8442799549aa.PNG)

Pages, waiting for a long time. 
Do we have a chance to remove font css?

if you want , I can send a pull request on this issue

**Comment by wakuflair** [comment]
I have noticed this problem , and a PR is very welcome:)

**Comment by onurcanyilmaz** [comment]
Resolved: https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE/issues/13
