### ISSUE TITLE
abp 3.1.2 not working

### ISSUE THREAD

**Issue by mucahiddanis** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#16]
![image](https://user-images.githubusercontent.com/16820194/94828613-5102ea00-0412-11eb-897b-fa25cf2aa0df.png)

**Comment by 15801824890** [comment]
the same problem

**Comment by wakuflair** [comment]
Sorry since lack of enough time and community support, this repo is no longer maintained.
You can search for alternatives, like https://github.com/csr2/Coso.Abp
