### ISSUE TITLE
Tenant management page not work on abp 4.3.0

### ISSUE THREAD

**Issue by dangminhbk** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#30]
Tenant management page not work on abp 4.3.0
![image](https://user-images.githubusercontent.com/31243225/117790993-14368580-b274-11eb-99aa-3befa15155cb.png)

It's seem that ConnectionStringModal.js was removed. in https://github.com/abpframework/abp/commit/eb55d640912026b3544e3cd8a4b1285bdd665aac

I comment out
       ` @*<abp-script src="/Pages/TenantManagement/Tenants/ConnectionStringsModal.js" />*@ `
 and the page is loaded, but some Create funtions still not work.

**Comment by dangminhbk** [comment]
@wakuflair check this pull request. #31 , it's also fix cannot create new Tenant on sample project.

**Comment by zhangliguo1986** [comment]
@dangminhbk
"/Pages/TenantManagement/Tenants/ConnectionStringsModal.js"  
This file has been removed in version 4.3

**Comment by wakuflair** [comment]
> @wakuflair if you have time, please check this pull request #31 .It's also fix cannot create new Tenant on sample project.

Thanks, I'll see it ASAP.

**Comment by wakuflair** [comment]
The PR has been merged, thank you guys!
