### ISSUE TITLE
Footer rendered in the wrong location

### ISSUE THREAD

**Issue by 274188A** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#32]
```

Abp 4.3.2
Abp.AspNetCore.Mvc.UI.Theme.AdminLTE 0.7.2
```

Just a small issue here but with  using with abp 4.3.2 the footer get placed in the wrong location (above the grid)

I compared it to the standards in the abp samples and my client mvc code seems ok there so assuming the theme is not quite correct?

![image](https://user-images.githubusercontent.com/40014477/120157084-38f39c80-c225-11eb-991d-e2557743f6f2.png)

**Comment by 274188A** [comment]
just again tested against latest stable Abp (4.3.2) and created a project using abp cli, replace the theme and could reproduce the same problem.

**Comment by scorpion86** [comment]
same here

**Comment by 274188A** [comment]
can you spell out the other errors you're seeing?  I'm trying to debug this...

**Comment by 274188A** [comment]
I took a further look and compared a view that works (eg list view of roles) and a custom view (list view of custom entity).  I saw there were a few differences in the layout.  I'm not strong in the area of css and html but I'm hoping if I post what I found here it might in some small way help us fix the problem

Below is a screen shot of two views - "working" (on the left) and "not working" (on the right)

![image](https://user-images.githubusercontent.com/40014477/120262579-7fe89d00-c2cc-11eb-93b2-4e1021c0416e.png)

**Comment by scorpion86** [comment]
@enisn if you have time can you take a look at this issue? I Added this theme as a project and upgraded the nuget packages also but still same. Pages already in the theme is working but the normal pages i added in the web project having the problem.

**Comment by 274188A** [comment]
@scorpion86 the abp framework keeps changing so breaks these 'free' themes.   these free themes are not good for volo's bank account so I'm starting to get a little suspicious that they are making it tough to live without a paid subscription to volo...

**Comment by scorpion86** [comment]
@274188A I'm not agree with you. They are realy a good company. Every company needs money to survive. But their open source projects are enough to start a small project.

**Comment by scorpion86** [comment]
It seems like problem is about abp-table tag helper. If i use 

<table class="table" id="GenderTable"></table>

instead of 

<abp-table id="GenderTable" />

then it seems ok.

**Comment by wakuflair** [comment]
@scorpion86 

Is it OK now? Can I close this issue?
