### ISSUE TITLE
/Pages/TenantManagement/Tenants/ConnectionStringsModal.js  file has been removed in version 4.3

### ISSUE THREAD

**Issue by zhangliguo1986** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#35]
"/Pages/TenantManagement/Tenants/ConnectionStringsModal.js"
This file has been removed in version 4.3

**Comment by wakuflair** [comment]
See https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE/issues/30
