### ISSUE TITLE
Error on Tenant Management Page

### ISSUE THREAD

**Issue by gfo2007** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#36]
Hi,
Thanks for the theme. Please after adding the theme to abp framework, I get the error below anytime I try to access the Tenant Management page.

Help please.

_**AbpException: Could not find the bundle file '/Pages/TenantManagement/Tenants/ConnectionStringsModal.js' for the bundle 'Volo.Abp.TenantManagement.Web.Pages.TenantManagement.Tenants.IndexModel'!**_

**Comment by wakuflair** [comment]
See https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE/issues/30.
I will publish a new version soon.

**Comment by gfo2007** [comment]
@wakuflair hi. Please have you been able to publish a new theme?

**Comment by wakuflair** [comment]
@gfo2007 hi, sorry for the late.
The new version package(0.7.3) has been published.

**Comment by gfo2007** [comment]
@wakuflair please the image below shows the errors I am getting.

![bookstore app adminui theme error](https://user-images.githubusercontent.com/14317420/135099082-8310bf72-3c1d-4bc3-bc21-9e9927a78cf5.PNG)

**Comment by gfo2007** [comment]
@wakuflair I needed to update abp framework. It is okay now. Let me test it.

Regards.

**Comment by gfo2007** [comment]
@wakuflair please how do you save changes you make with the colours you have provided on the theme?

Anytime I make changes and I click on another menu, it goes back the the black sidebar background.

Regards

**Comment by wakuflair** [comment]
@gfo2007 
That's not been implemented.
You could raise another issue to discuss it.
