### ISSUE TITLE
远程css资源异常

### ISSUE THREAD

**Issue by luy710** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#8]
https://fonts.cat.net/css无法加载

**Comment by jonny-xhl** [comment]
## load css file is error
Now,I use `AdminLTE`,but the css file is load error.
[https://fonts.cat.net/css?family=Source+Sans+Pro:300,400,400i,700](https://fonts.cat.net/css?family=Source+Sans+Pro:300,400,400i,700)

What is the problem?

**Comment by wakuflair** [comment]
Fixed by https://github.com/wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE/pull/13
