### ISSUE TITLE
Selected page does not appear actively in the menu.

### ISSUE THREAD

**Issue by onurcanyilmaz** [wakuflair/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE#9]
Firstly, very nice job. Thank you much.

My issue,
When Turkish language is selected, sidebar menu active page does not appearing. But other languages working

![test](https://user-images.githubusercontent.com/33642676/82673132-0e522980-9c4a-11ea-9b59-b45edc5755dd.PNG)

Can you help me?
Thanks...

**Comment by wakuflair** [comment]
Hi @onurcanyilmaz 
I can't reproduce your issue, it worked well on my computer:
![image](https://user-images.githubusercontent.com/3471718/82722921-40709380-9cfd-11ea-8d2e-26fa38b69422.png)

**Comment by wakuflair** [comment]
Recently, I publish a [new package](https://www.nuget.org/packages/Abp.AspNetCore.Mvc.UI.Theme.AdminLTE/0.6.2) that support the latest ABP version(v2.8).
Try it to see if the issue still exists.

**Comment by onurcanyilmaz** [comment]
Hello again @wakuflair ,

Sorry, what I would like to say, left  nav bar not showing  active page 
Look at pictures please

not show active page in tr:
----------
![tr_not_active_class](https://user-images.githubusercontent.com/33642676/82730091-ba0c7f80-9d05-11ea-8ccc-23a1c2e0a618.PNG)

showing other languages active page:
--------

![en_active_class](https://user-images.githubusercontent.com/33642676/82730098-d14b6d00-9d05-11ea-92b7-180b9c3e6e37.PNG)

------
![zn_active](https://user-images.githubusercontent.com/33642676/82730164-6b131a00-9d06-11ea-8992-2e218ca5be7f.PNG)

Turkish language is not working.
thanks a lot

**Comment by wakuflair** [comment]
Hi @onurcanyilmaz 
It's a string comparision bug, I have fixed it.
Thank you for your feedback!
